const app=document.getElementById('app');
const state={stars:Number(localStorage.getItem('constance-stars')||0),memoryLock:false};
const reward=(n=1)=>{state.stars+=n;localStorage.setItem('constance-stars',state.stars);tone(740,.08);setTimeout(()=>tone(980,.12),90)};
function tone(freq=440,d=.08){try{const A=window.AudioContext||window.webkitAudioContext;const c=new A();const o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.stop(c.currentTime+d+.02)}catch(e){}}
function shell(content){app.innerHTML=`<section class="screen"><div class="stars"></div>${content}</section>`}
function home(){shell(`<div class="topbar"><div class="brand"><h1>Le Royaume magique de <span class="gold">Constance</span></h1><div class="subtitle">Choisis ton aventure ✨</div></div><div class="pill score">⭐ <span>${state.stars}</span></div></div><div class="hero-card"><div class="world"><div class="moon"></div><div class="castle">🏰</div><div class="river"></div><div class="fairy">🧚‍♀️</div><div class="dragon">🐉</div><div class="avatar">👧🏽‍♀️</div><div class="youpiii">🐰</div><div class="hint">Coucou Constance ! Je suis Youpiii. Quelle aventure choisis-tu ?</div>${island('i1','🌀 Forêt des Fées','Labyrinthe','maze')}${island('i2','🔤 Château de la Princesse','Lettres & mots','words')}${island('i3','🔢 Grotte du Dragon','Chiffres','numbers')}${island('i4','🔎 Jardin enchanté','5 différences','diff')}${island('i5','⭐ Tour des Étoiles','Memory','memory')}${island('i6','➕ Pont magique','Additions','addition')}</div></div><div class="footer-note">Pas de chrono • Pas de punition • Chaque bouton fonctionne hors connexion</div>`)}
function island(pos,title,sub,id){return `<div class="island ${pos}"><button onclick="openGame('${id}')">${title}<br><small>${sub}</small></button></div>`}
window.openGame=id=>({maze,words,numbers,diff,memory,addition}[id]||home)();
function gameWrap(title,body){shell(`<div class="game-screen"><div class="game-card"><div class="game-title"><button class="back" onclick="home()">← Royaume</button><h2>${title}</h2><div class="pill">⭐ ${state.stars}</div></div>${body}</div></div>`)}
function numbers(){const correct=1+Math.floor(Math.random()*9);let opts=[correct];while(opts.length<3){let n=1+Math.floor(Math.random()*9);if(!opts.includes(n))opts.push(n)}opts.sort(()=>Math.random()-.5);gameWrap('🔢 Les chiffres',`<div class="instruction">Touche le chiffre <b>${correct}</b></div><div class="answers">${opts.map(n=>`<button class="big-answer" onclick="checkSimple(${n===correct})">${n}</button>`).join('')}</div><div id="fb" class="feedback"></div>`)}
window.checkSimple=ok=>{const f=document.getElementById('fb');if(ok){f.textContent='Bravo Constance ! ⭐';f.className='feedback success';reward();setTimeout(()=>numbers(),900)}else{f.textContent='Presque ! Essaie encore ✨';f.className='feedback soft';tone(260,.06)}};
function addition(){const a=1+Math.floor(Math.random()*4),b=1+Math.floor(Math.random()*4),sum=a+b;let opts=[sum];while(opts.length<3){let n=2+Math.floor(Math.random()*8);if(!opts.includes(n))opts.push(n)}opts.sort(()=>Math.random()-.5);gameWrap('➕ Petites additions',`<div class="instruction">Combien y a-t-il d’étoiles en tout ?</div><div class="objects">${'⭐'.repeat(a)} + ${'⭐'.repeat(b)}</div><div class="answers">${opts.map(n=>`<button class="big-answer" onclick="checkAdd(${n===sum})">${n}</button>`).join('')}</div><div id="fb" class="feedback"></div>`)}
window.checkAdd=ok=>{const f=document.getElementById('fb');if(ok){f.textContent='Magique ! Tu as trouvé ⭐';f.className='feedback success';reward();setTimeout(addition,900)}else{f.textContent='On recompte ensemble ✨';f.className='feedback soft';tone(260,.06)}};
function words(){const items=[['CHAT','🐱'],['FÉE','🧚‍♀️'],['DRAGON','🐉'],['ROI','🤴'],['LUNE','🌙'],['POMME','🍎']];const pick=items[Math.floor(Math.random()*items.length)];let pics=[pick];while(pics.length<4){let p=items[Math.floor(Math.random()*items.length)];if(!pics.find(x=>x[0]===p[0]))pics.push(p)}pics.sort(()=>Math.random()-.5);gameWrap('🔤 Lettres & mots',`<div class="instruction">Relie le mot à la bonne image</div><div class="word-grid"><div class="word">${pick[0]}</div><div class="pictures">${pics.map(p=>`<button class="picture" onclick="checkWord(${p[0]===pick[0]})">${p[1]}</button>`).join('')}</div></div><div id="fb" class="feedback"></div>`)}
window.checkWord=ok=>{const f=document.getElementById('fb');if(ok){f.textContent='Oui ! Très bien 🌟';f.className='feedback success';reward();setTimeout(words,900)}else{f.textContent='Ce n’est pas celle-ci. Regarde encore 💫';f.className='feedback soft';tone(260,.06)}};
function memory(){const emojis=['🧚‍♀️','🐉','👑','⭐','🦄','💎'];let deck=[...emojis,...emojis].sort(()=>Math.random()-.5);window._mem={deck,open:[],done:new Set()};gameWrap('⭐ Jeu de mémoire',`<div class="instruction">Retrouve toutes les paires</div><div class="memory">${deck.map((_,i)=>`<button id="m${i}" class="card" onclick="flip(${i})">✨</button>`).join('')}</div><div id="fb" class="feedback"></div>`)}
window.flip=i=>{const m=window._mem;if(state.memoryLock||m.done.has(i)||m.open.includes(i))return;const btn=document.getElementById('m'+i);btn.classList.add('open');btn.textContent=m.deck[i];m.open.push(i);tone(520,.05);if(m.open.length===2){state.memoryLock=true;const[a,b]=m.open;if(m.deck[a]===m.deck[b]){m.done.add(a);m.done.add(b);m.open=[];state.memoryLock=false;tone(800,.08);if(m.done.size===m.deck.length){document.getElementById('fb').textContent='Bravo ! Toutes les paires sont trouvées ⭐';reward(2)}}else setTimeout(()=>{[a,b].forEach(x=>{const q=document.getElementById('m'+x);q.classList.remove('open');q.textContent='✨'});m.open=[];state.memoryLock=false},650)}};
const mazeMap=[['.','.','#','.','.','.'],['#','.','#','.','#','.'],['.','.','.','.','#','.'],['.','#','#','.','.','.'],['.','.','.','#','#','.'],['#','#','.','.','.','G']];
function maze(){window._pos={r:0,c:0};renderMaze('Trouve le dragon !')}
function renderMaze(msg=''){let html='';mazeMap.forEach((row,r)=>row.forEach((v,c)=>{const p=window._pos.r===r&&window._pos.c===c;html+=`<div class="cell ${v==='#'?'wall':''} ${p?'player':''} ${v==='G'?'goal':''}">${p?'👧🏽‍♀️':v==='G'?'🐉':''}</div>`}));gameWrap('🌀 Labyrinthe magique',`<div class="instruction">${msg}</div><div class="maze">${html}</div><div class="controls"><span class="blank"></span><button onclick="move(-1,0)">↑</button><span class="blank"></span><button onclick="move(0,-1)">←</button><button onclick="move(1,0)">↓</button><button onclick="move(0,1)">→</button></div><div id="fb" class="feedback"></div>`)}
window.move=(dr,dc)=>{const nr=window._pos.r+dr,nc=window._pos.c+dc;if(nr<0||nc<0||nr>=6||nc>=6||mazeMap[nr][nc]==='#'){tone(240,.05);return}window._pos={r:nr,c:nc};if(mazeMap[nr][nc]==='G'){reward(2);renderMaze('Bravo ! Tu as retrouvé le dragon ⭐')}else renderMaze('Continue, tu es sur le bon chemin ✨')};
function diff(){const base=[['☁️',10,15],['🌈',55,8],['🦋',25,55],['🌸',68,65],['🐇',45,72],['⭐',78,35]];const changed=new Set([1,3,5]);window._diffFound=new Set();const scene=side=>`<div class="scene">${base.map((o,i)=>{let emoji=o[0];if(side===1&&changed.has(i))emoji=['☀️','🌷','🌙'][[...changed].indexOf(i)];return `<button class="obj" style="left:${o[1]}%;top:${o[2]}%" onclick="tapDiff(${i})">${emoji}</button>`}).join('')}</div>`;gameWrap('🔎 Les 5 différences',`<div class="instruction">Trouve les 3 différences de ce niveau</div><div class="diff-wrap">${scene(0)}${scene(1)}</div><div id="fb" class="feedback">0 / 3 trouvées</div>`)}
window.tapDiff=i=>{const targets=new Set([1,3,5]),f=document.getElementById('fb');if(targets.has(i)){window._diffFound.add(i);f.textContent=`${window._diffFound.size} / 3 trouvées ⭐`;tone(760,.06);if(window._diffFound.size===3){f.textContent='Bravo ! Tu as tout trouvé 🌟';reward(2)}}else{f.textContent='Regarde bien… une luciole va t’aider ✨';tone(250,.05)}};
window.home=home;home();
